# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='АИС', max_length=50, verbose_name='Краткое название')),
                ('full_name', models.CharField(blank=True, default='АИС', max_length=150, null=True, verbose_name='Полное название')),
            ],
            options={
                'ordering': ['short_name'],
                'verbose_name_plural': 'Системы',
                'verbose_name': 'Система',
            },
        ),
    ]
