# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0002_isystem_developer'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='message_text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
    ]
