# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 19:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0003_isystem_message_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isystem',
            old_name='message_text',
            new_name='description',
        ),
    ]
