# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0004_auto_20170104_0505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='в промышленной эксплуатации', max_length=100, verbose_name='Статус')),
                ('status_date', models.DateField(blank=True, null=True, verbose_name='Дата присвоения статуса')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='isystems.iSystem', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Статус',
                'ordering': ['system', '-status_date'],
                'verbose_name_plural': 'Статусы',
            },
        ),
    ]
