# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0006_status_link_eatd'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='support_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о технической поддержке'),
        ),
    ]
