# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0007_isystem_support_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='lic_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация о лицензировании'),
        ),
        migrations.AlterField(
            model_name='isystem',
            name='full_name',
            field=models.CharField(blank=True, default='АИС', max_length=500, null=True, verbose_name='Полное название'),
        ),
    ]
