# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-21 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0010_auto_20170228_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='status',
            name='cost_currency',
        ),
        migrations.RemoveField(
            model_name='status',
            name='nds',
        ),
        migrations.RemoveField(
            model_name='status',
            name='nds_currency',
        ),
    ]
