# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-21 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0011_auto_20170621_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Проект')),
            ],
            options={
                'verbose_name_plural': 'Проекты',
                'verbose_name': 'Проект',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='isystem',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_systems', to='isystems.Project', verbose_name='Проект'),
        ),
    ]
