# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-22 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0012_auto_20170621_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='system_type',
            field=models.CharField(blank=True, choices=[('Локальная', 'Локальная'), ('Корпоративная', 'Корпоративная')], default='Локальная', max_length=20, null=True, verbose_name='Тип системы'),
        ),
    ]
