# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-22 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0013_isystem_system_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='system_function',
            field=models.CharField(blank=True, choices=[('Производственная система', 'Производственная система'), ('Административная система', 'Административная система')], default='', max_length=50, null=True, verbose_name='Назначение системы'),
        ),
    ]
