# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-26 00:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0013_people_info'),
        ('isystems', '0015_auto_20170623_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='administrator',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='administrator_systems', to='people.Organization_Based_Role', verbose_name='Администратор'),
        ),
    ]
