# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-15 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0018_isystem_info_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='critical',
            field=models.BooleanField(default=False, verbose_name='Критичность для функционирования организации'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('в опытной эксплуатации', 'в опытной эксплуатации'), ('завершена опытная эксплуатация', 'завершена опытная эксплуатация'), ('в промышленной эксплуатации', 'в промышленной эксплуатации')], default='в промышленной эксплуатации', max_length=100, verbose_name='Статус'),
        ),
    ]
