# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-15 02:18
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0019_auto_20170715_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='functional_customer',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Все отделы и службы', 'Все отделы и службы'), ('ОИТ', 'Отдел информационных технологий'), ('ТТО', 'Товарно-транспортная служба'), ('ЮО', 'Юридический отдел')], default='', max_length=20, null=True, verbose_name='Функциональные заказчики'),
        ),
    ]
