# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-15 02:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20170417_1711'),
        ('isystems', '0020_isystem_functional_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='maintenance',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ment_systems', to='organizations.Organization', verbose_name='Техническое сопровождение'),
        ),
        migrations.AlterField(
            model_name='isystem',
            name='functional_customer',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Все отделы и службы', 'Все отделы и службы'), ('ОГМетр', 'Отдел главного метролога'), ('ОИТ', 'Отдел информационных технологий'), ('ОК', 'Отдел кадров'), ('ОМ', 'Отдел мониторинга'), ('ООП', 'Отдел общественного питания'), ('ОПиПТ', 'Отдел планирования и проведения торгов'), ('СОК', 'Служба общественных коммуникаций'), ('СОТ', 'Служба охраны труда'), ('ТТО', 'Товарно-транспортная служба'), ('ЮО', 'Юридический отдел')], default='', max_length=20, null=True, verbose_name='Функциональные заказчики'),
        ),
    ]
