# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-26 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0021_auto_20170715_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='link_eatd',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на отчетный документ'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('в опытной эксплуатации', 'в опытной эксплуатации'), ('завершена опытная эксплуатация', 'завершена опытная эксплуатация'), ('в промышленной эксплуатации', 'в промышленной эксплуатации'), ('первичная закупка', 'первичная закупка')], default='в промышленной эксплуатации', max_length=100, verbose_name='Статус'),
        ),
    ]
