# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 02:52
from __future__ import unicode_literals

from django.db import migrations, models
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0022_auto_20170726_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Life_Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.CharField(max_length=200, verbose_name='Этап жизненного цикла ИС')),
                ('position', positions.fields.PositionField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Этапы жизненного цикла ИС',
                'ordering': ['position'],
                'verbose_name': 'Этап жизненного цикла ИС',
            },
        ),
    ]
