# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 02:56
from __future__ import unicode_literals

from django.db import migrations
import positions.fields


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0023_life_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='life_step',
            name='position',
            field=positions.fields.PositionField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
