# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 03:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0024_auto_20170815_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='life_step',
            options={'ordering': ['position', 'step'], 'verbose_name': 'Этап жизненного цикла ИС', 'verbose_name_plural': 'Этапы жизненного цикла ИС'},
        ),
    ]
