# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-17 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0026_auto_20170817_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='abbreviation',
            field=models.CharField(default='AIS', help_text='Латинскими прописными буквами, допускается символ подчеркивания', max_length=20, verbose_name='Аббревиатура'),
        ),
    ]
