# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_responsibilitycenter'),
        ('isystems', '0029_auto_20171017_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='isystem',
            name='responsibility_center',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.ResponsibilityCenter', verbose_name='Ответственный за сопровождение'),
        ),
        migrations.AddField(
            model_name='isystem',
            name='shadow',
            field=models.BooleanField(default=False, help_text='ИТ-устройства, ПО и сервисы, которые присутствуют в организации, но не обслуживаются ИТ-отделом.', verbose_name='Теневая система'),
        ),
    ]
