# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0030_auto_20171207_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isystem',
            name='short_name',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Краткое название'),
        ),
    ]
