# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whats_new_message', models.TextField(verbose_name='Что нового')),
                ('release_date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Что нового',
                'verbose_name': 'Что нового',
                'ordering': ['-release_date_time'],
            },
        ),
    ]
