# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='reg_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
