# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0006_status_link_eatd'),
        ('contracts', '0002_auto_20170110_0319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='sed_link',
        ),
        migrations.AddField(
            model_name='contract',
            name='link_sed',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на договор в СЭД'),
        ),
        migrations.AddField(
            model_name='contract',
            name='system',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='isystems.iSystem', verbose_name='Система'),
        ),
    ]
