# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20170113_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='sed_project_number',
        ),
        migrations.AddField(
            model_name='contract',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Действует по'),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Действует с'),
        ),
    ]
