# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 01:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20170228_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='ext_number',
        ),
    ]
