# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('isystems', '0006_status_link_eatd'),
        ('contracts', '0003_auto_20170113_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='План-график', max_length=300, verbose_name='Название графика')),
                ('contract', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='contracts.Contract', verbose_name='Договор')),
                ('system', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='isystems.iSystem', verbose_name='Система')),
            ],
            options={
                'verbose_name_plural': 'План-графики',
                'ordering': ['system'],
                'verbose_name': 'План-график',
            },
        ),
    ]
