# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-08 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_charts', '0004_auto_20170208_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='status',
            new_name='done',
        ),
    ]
