# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_charts', '0006_auto_20170214_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='man_executors',
            field=models.ManyToManyField(blank=True, null=True, to='people.People', verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='step',
            name='org_executors',
            field=models.ManyToManyField(blank=True, null=True, to='organizations.Organization', verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='step',
            name='repoper',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Результат этапа'),
        ),
    ]
