# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_charts', '0007_auto_20170214_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='man_executors',
            field=models.ManyToManyField(blank=True, to='people.People', verbose_name='Исполнители'),
        ),
        migrations.AlterField(
            model_name='step',
            name='org_executors',
            field=models.ManyToManyField(blank=True, to='organizations.Organization', verbose_name='Исполнители'),
        ),
    ]
