# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_charts', '0008_auto_20170214_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='repoper',
            new_name='report',
        ),
    ]
