# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-20 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_charts', '0012_auto_20170220_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['date_begin'], 'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
    ]
