# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_charts', '0013_auto_20170220_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='milestone',
            field=models.BooleanField(default=False, verbose_name='Важный этап'),
        ),
    ]
