# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-22 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_charts', '0014_step_milestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['date_begin', '-date_end'], 'verbose_name': 'Этап', 'verbose_name_plural': 'Этапы'},
        ),
    ]
