# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(default='', max_length=200, verbose_name='Краткое название')),
                ('full_name', models.CharField(default='', max_length=200, verbose_name='Полное название')),
            ],
            options={
                'verbose_name_plural': 'Организации',
                'ordering': ['short_name'],
                'verbose_name': 'Организация',
            },
        ),
    ]
