# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20170414_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_name',
            field=models.CharField(default='', max_length=200, unique=True, verbose_name='Краткое название'),
        ),
    ]
