# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_auto_20170417_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='Краткое название')),
                ('full_name', models.CharField(max_length=200, unique=True, verbose_name='Полное название')),
            ],
            options={
                'verbose_name_plural': 'Отделы',
                'verbose_name': 'Отдел',
            },
        ),
    ]
