# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 03:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['short_name', 'full_name'], 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
    ]
