# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20170815_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsibilityCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='Краткое название')),
                ('full_name', models.CharField(max_length=200, unique=True, verbose_name='Полное название')),
            ],
            options={
                'verbose_name': 'Центр ответственности',
                'ordering': ['short_name', 'full_name'],
                'verbose_name_plural': 'Центр ответственности',
            },
        ),
    ]
