# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-17 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20170417_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='ogrn',
            field=models.CharField(blank=True, default=0, max_length=50, unique=True, verbose_name='ОГРН'),
            preserve_default=False,
        ),
    ]
