# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-15 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20170815_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на документ'),
        ),
    ]
