# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('people', '0002_people_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='people', to='organizations.Organization', verbose_name='Организация'),
        ),
    ]
