# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-01 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_auto_20170102_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='organization',
        ),
    ]
