# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('people', '0007_auto_20170102_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization_Based_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Должность')),
                ('organization', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organizations.Organization', verbose_name='Организация')),
                ('people', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='people.People', verbose_name='Работник')),
            ],
            options={
                'ordering': ['people'],
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
    ]
