# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_organization_based_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='@', max_length=100, verbose_name='email')),
                ('base_mail', models.BooleanField(default=True, verbose_name='Основной адрес')),
                ('people', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='people.People', verbose_name='Работник')),
            ],
            options={
                'verbose_name_plural': 'emails',
                'ordering': ['email'],
                'verbose_name': 'email',
            },
        ),
    ]
