# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='', max_length=100, verbose_name='Номер телефона')),
                ('people', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='people.People', verbose_name='Работник')),
            ],
            options={
                'verbose_name_plural': 'Телефоны',
                'verbose_name': 'Телефон',
                'ordering': ['phone_number'],
            },
        ),
        migrations.CreateModel(
            name='Phone_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.CharField(max_length=100, verbose_name='Тип телефонной связи')),
            ],
            options={
                'verbose_name_plural': 'Типы телефонной связи',
                'verbose_name': 'Тип телефонной связи',
                'ordering': ['phone_type'],
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='phone_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='people.Phone_Type', verbose_name='Тип телефонной связи'),
        ),
    ]
