# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isystems', '0006_status_link_eatd'),
        ('people', '0010_auto_20170113_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_Based_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=250, verbose_name='Роль')),
                ('people', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sys_roles', to='people.People', verbose_name='Работник')),
                ('system', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sys_roles', to='isystems.iSystem', verbose_name='Система')),
            ],
            options={
                'verbose_name': 'Роль',
                'ordering': ['people', 'system'],
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.AlterField(
            model_name='organization_based_role',
            name='organization',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='organizations.Organization', verbose_name='Организация'),
        ),
        migrations.AlterField(
            model_name='organization_based_role',
            name='people',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='org_roles', to='people.People', verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='organization_based_role',
            name='post',
            field=models.CharField(default='', max_length=250, verbose_name='Должность'),
        ),
    ]
