# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20170116_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Дополнительная информация'),
        ),
    ]
